/**
 * Creating a sidebar enables you to:
 - Create an ordered group of docs
 - Render a sidebar in the docs side navigation (normally on the left)
 - Learn more about Docusaurus sidebars: https://docusaurus.io/docs/sidebar
 */

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Module 1: The Robotic Nervous System (ROS 2)',
      link: {
        type: 'generated-index',
        title: 'Module 1',
        description: 'Learn about ROS 2 core concepts and building robot software.',
        slug: '/module1',
      },
      items: [{type: 'autogenerated', dirName: 'module1'}],
    },
    {
      type: 'category',
      label: 'Module 2: The Digital Twin (Gazebo & Unity)',
      link: {
        type: 'generated-index',
        title: 'Module 2',
        description: 'Explore creating realistic simulation environments for humanoid robots.',
        slug: '/module2',
      },
      items: [{type: 'autogenerated', dirName: 'module2'}],
    },
    {
      type: 'category',
      label: 'Module 3: The AI-Robot Brain (NVIDIA Isaac™)',
      link: {
        type: 'generated-index',
        title: 'Module 3',
        description: 'Endow humanoid robots with perception, navigation, and learning intelligence using NVIDIA Isaac.',
        slug: '/module3',
      },
      items: [{type: 'autogenerated', dirName: 'module3'}],
    },
    {
      type: 'category',
      label: 'Module 4: Vision-Language-Action (VLA) & The Autonomous Humanoid Capstone',
      link: {
        type: 'generated-index',
        title: 'Module 4',
        description: 'Fuse language, vision, and robotics into a fully autonomous humanoid system.',
        slug: '/module4',
      },
      items: [{type: 'autogenerated', dirName: 'module4'}],
    },
    {
      type: 'category',
      label: 'Architecture & Lab Infrastructure',
      link: {
        type: 'generated-index',
        title: 'Architecture & Labs',
        description: 'Design on-prem and cloud-based Physical AI labs, select edge devices and sensors.',
        slug: '/architecture',
      },
      items: [{type: 'autogenerated', dirName: 'architecture'}],
    },
  ],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document', 'tutorial-basics/create-a-blog-post', 'tutorial-basics/create-a-page'],
    },
  ],
   */
};

module.exports = sidebars;
